name: JustQuest
main: net.sakuragame.eternal.justquest.JustQuest
version: ${project.version}
author: 'justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - DataManager
  - DragonCore
  - UIFactory
  - Adyeshach
  - Zaphkiel
  - MythicMobs
  - DragonArmourers
  - JustLevel
  - GemsEconomy
  - JustMessage
  - JustAttribute
softdepend:
  - KirraDungeonCommon
  - KirraPartyBukkit
  - JustStore
  - JustAlchemy
  - KirraMiner

commands:
  jquest:
    aliases:
      - quest
    description: show all command