name: JustQuest
main: net.sakuragame.eternal.justquest.JustQuest
version: ${project.version}
author: 'justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - DragonCore
  - UIFactory
  - Adyeshach
  - Zaphkiel
  - MythicMobs
  - JustStore
softdepend:
  - KirraPartyBukkit

commands:
  jquest:
    aliases:
      - quest
    description: show all command